sudo: false
cache:
  directories:
    - extlib/
    - $HOME/.cpanm/
    - $HOME/.grails/
    - jbrowse-download/
language: groovy
script:
    - ant gwtc && ./grailsw refresh-dependencies --stacktrace && ./grailsw test-app --stacktrace
    - node web-app/jbrowse/src/dojo/dojo.js load=build --require "web-app/jbrowse/src/JBrowse/init.js" --profile "web-app/jbrowse/plugins/WebApollo/js/WebApollo"
