site_name: Web Apollo 2.0
pages:
- ['index.md', 'Index']
- ['Introduction.md', 'Introduction']
- ['Prerequisites.md', 'Pre-requisites']
- ['Apollo2Build.md', 'Web Apollo 2.0 quick-setup']
- ['Configure.md', 'Configure']
- ['Data_loading.md', 'Data loading']
- ['Build.md', 'Build']
- ['Troubleshooting.md', 'Troubleshooting']
- ['Developer.md', 'Developers guide']
- ['Testing_notes.md', 'Testing notes']

